import AboutPage from "@/components/views/components/about/about";
import Head from "next/head";
import React from "react";

const About = () => {
  return (
    <>
      <Head>
        <title>About PSPAY - Mobile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <AboutPage />
    </>
  );
};

export default About;
About.layout = "main";
