import AboutUs from "@/components/home/about-us/about-us";
import BackToTop from "@/components/home/back-to-top-button/backToTop";
import Banner from "@/components/home/banner/banner";
import Cryptocurrencies from "@/components/home/cryptocurrencies/cryptocurrencies";
import Faq from "@/components/home/faq/faq";
import FastAccess from "@/components/home/fast-access/fast-access";
import FeaturedIn from "@/components/home/featured-in/featured-in";
import Recognitions from "@/components/home/recognitions/recognitions";
import Starttrading from "@/components/home/start-trading/start-trading";
import WhoPspay from "@/components/home/who-pspay/who-pspay";
import Head from "next/head";

Home.layout = "main";
export default function Home() {
  return (
    <>
      <Head>
        <title>PSPAY - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <div className="home-page-content">
        <Banner />
        <Cryptocurrencies />
        <FeaturedIn />
        {/* <FastAccess /> */}
        <Starttrading />
        <AboutUs header={true} />
        {/* <Recognitions /> */}
        <WhoPspay />
        <Faq />
        <BackToTop />
      </div>
    </>
  );
}
