import MobilePage from "@/components/views/components/mobile/mobile";
import Head from "next/head";

const Mobile = () => {
  return (
    <>
      <Head>
        <title>PSPAY - Mobile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <MobilePage />
    </>
  );
};

export default Mobile;
Mobile.layout = "main";
