import SignUpPage from "@/components/views/components/authorization/signup";
import Head from "next/head";

const Register = () => {
  return (
    <>
      <Head>
        <title>PSPAY - SignUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <SignUpPage />
    </>
  );
};

export default Register;
Register.layout = "nav";
