import SignInPage from "@/components/views/components/authorization/signin";
import Head from "next/head";

const SignIn = () => {
  return (
    <>
      <Head>
        <title>PSPAY - SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <SignInPage />
    </>
  );
};

export default SignIn;
