import SignInPage from "@/components/views/components/authorization/signin";
import Navbar from "layouts/main-layout/components/navbar/navbar";
import Head from "next/head";
import styled from "styled-components";

const NavStyled = styled.nav`
  position: sticky;
  top: 0;
  z-index: 100;
  border-bottom: 1px solid #ebeef2;
  box-shadow: 0 5px 10px rgb(0 0 0 / 5%);
  background-color: #fff;
  color: #26374c;
  font-size: 0.9rem;
  width: 100%;
`;

const SignIn = () => {
  return (
    <>
      <Head>
        <title>PSPAY - SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <NavStyled>
        <Navbar />
        <SignInPage />
      </NavStyled>
      {/* <SignInPage /> */}
    </>
  );
};

export default SignIn;
