import BlogDetailsPage from "@/components/views/components/blog/blog-details";
import Head from "next/head";
import React from "react";

const BlogDetails = () => {
  return (
    <>
      <Head>
        <title>PSPAY - Blog Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <BlogDetailsPage />
    </>
  );
};

export default BlogDetails;
BlogDetails.layout = "main";
